<?php

/**
 *  Generated by IceTea Framework 0.0.1
 *  Created at 2017-11-12 10:05:19
 *  Namespace App\Http\Controllers\Auth
 */

namespace App\Http\Controllers\Auth;

use IceTea\Http\Controller;

class LoginController extends Controller
{
    public function __construct()
    {
        parent::__construct();
    }

    public function index()
    {
        //
    }

    public function csrf_token()
    {
        return ice_encrypt(
            json_encode(
                [
                    "expired" => time() + 3600
                ]
            ), "teamessenger123"
        );
    }

    public function loginPage()
    {
        return view("auth/login", ["that" => $this]);
    }

    public function indexLogin()
    {
        return $this->loginPage();
    }

    public function action()
    {
        $input = json_decode(file_get_contents("php://input"), true);
        if (isset(
            $input['username'],
            $input['password'],
            $input['csrf']
        )) {
            
        }
    }
}
