<?php

/**
 *	Generated by IceTea Framework 0.0.1
 *	Created at 2018-01-04 16:32:31
 *	Namespace App\Http\Controllers\Background
 */

namespace App\Http\Controllers\Background;

use IceTea\Http\Controller;

class NotificationController extends Controller
{
	public function __construct()
	{
		parent::__construct();
	}

    public function index()
    {
    	//
    }
}
