<?php

/**
 *  Generated by IceTea Framework 0.0.1
 *  Created at 2017-12-13 23:19:42
 *  Namespace App
 */

namespace App;

use PDO;
use App\User;
use IceTea\Database\DB;
use IceTea\Support\Model;

class Chat extends Model
{
    public function __construct()
    {
        parent::__construct();
    }

    public static function getList($user_id)
    {
        // $st = DB::prepare("SELECT `private_me`")
    }

    /**
     * @param string $self  user_id
     * @param string $to    username
     */
    public static function getChatInfo($self, $to)
    {
        return User::getInfo($to, "a.username");
    }

    public static function getChatRoom($self, $username)
    {
        // $st = DB::prepare("SELECT ");
        return [
            // ["ammarfaizi2", "halo"]
        ];
    }
}
