<?php

/**
 *	Generated by IceTea Framework 0.0.1
 *	Created at 2017-12-29 21:58:46
 *	Namespace App
 */

namespace App;

use IceTea\Database\DB;
use IceTea\Support\Model;

class GroupChat extends Model
{
	public function __construct()
	{
		parent::__construct();
	}

    public static function getChatInfo($self, $to)
    {
        //return User::getInfo($to, "a.username");
    }	

    public static function privatePost($sender, $receiver, $text)
    {
    	//
    }
}
