<?php

/**
 *	Generated by IceTea Framework 0.0.1
 *	Created at 2017-12-13 17:53:00
 *	Namespace App
 */

namespace App;

use PDO;
use IceTea\Database\DB;
use IceTea\Support\Model;

class Login extends Model
{
	public function __construct()
	{
		parent::__construct();
	}

	public function validateCredentials($identity, $password)
	{
		$field = filter_var($identity, FILTER_VALIDATE_EMAIL) ? "email" : (is_numeric($identity) ? "user_id" : "username");
		$st = DB::prepare("SELECT `password` FROM `users` WHERE `{$field}`=:bind LIMIT 1;");
		pc($st->execute([":bind" => $identity]), $st);
		if ($st = $st->fetch(PDO::FETCH_NUM)) {
			return password_verify($password, $st[0]);
		}
		return false;
	}
}
