<?php

/**
 *	Generated by IceTea Framework 0.0.1
 *	Created at 2017-12-13 15:36:30
 *	Namespace App
 */

namespace App;

use IceTea\Support\Model;

class Register extends Model
{
	public function __construct()
	{
		parent::__construct();
	}
}
