<?php

/**
 *	Generated by IceTea Framework 0.0.1
 *	Created at 2017-12-13 17:33:03
 *	Namespace App
 */

namespace App;

use PDO;
use IceTea\Database\DB;
use IceTea\Support\Model;

class User extends Model
{

	public function __construct()
	{
		parent::__construct();
	}

	public static function getInfo($value, $field, $table = "users")
	{
		$st = DB::prepare("SELECT `a`.`user_id`,`a`.`username`,`a`.`email`,`a`.`verified`,`a`.`status`,`a`.`registered_at`,`b`.`first_name`,`b`.`last_name`,`b`.`photo`,`b`.`bio` FROM `users` AS `a` INNER JOIN `users_info` AS `b` ON `a`.`user_id`=`b`.`user_id` WHERE {$field} = :bind LIMIT 1;");
		pc($st->execute(
			[
				":bind" => $value
			]
		), $st);
		return $st->fetch(PDO::FETCH_ASSOC);
	}
}
