<?php

/**
 *  Generated by IceTea Framework 0.0.1
 *  Created at 2017-12-14 12:20:34
 *  Namespace App\Http\Controllers\Profile
 */

namespace App\Http\Controllers\Profile;

use App\User;
use App\Login;
use IceTea\Http\Controller;
use App\Http\Controllers\Auth\CSRFToken;
use App\Http\Controllers\Auth\JSONResponse;

class ChangeInfo extends Controller
{
    use CSRFToken, JSONResponse;

    public function __construct()
    {
        header("Content-type:application/json");
        parent::__construct();
    }

    public function index()
    {
        //
    }

    public function run()
    {
        $input = json_decode(file_get_contents("php://input"), true);
        if (isset(
            $input['first_name'],
            $input['last_name'],
            $input['username'],
            $input['email'],
            $input['csrf'],
            $input['cost']
        )) {
            if (! $this->csrfValidation($input['csrf'])) {
                $this->err("Token mismatch", "?err=token_mismatch&w=".urlencode(rstr(64)));
            }
            $this->validate($input);
            $this->update($input);
        }
    }

    private function validate($input)
    {
        empty($input['first_name']) and $this->err("Invalid first name!");
        filter_var($input['email'], FILTER_VALIDATE_EMAIL) or $this->err("Invalid email!");
        $len = strlen($input['username']);
        $len > 3  or $this->err("Username too short, please provide username more than 4 characters!");
        $len < 33 or $this->err("Username too long, please provide username less than 32 characters!");
    }

    public function update($input)
    {
        if (User::changeInfo(Login::getUserId(), $input)) {
            exit($this->buildJson(
                [
                        "status"  => "ok",
                        "message" => "Success",
                        "redirect"=> "/profile?ref=change_info&w=".urlencode(rstr(64))
                    ]
            ));
        } else {
            $this->err("Internal error", "");
        }
    }
}
