<?php

/**
 *	Generated by IceTea Framework 0.0.1
 *	Created at 2017-12-14 14:02:23
 *	Namespace App\Http\Controllers\Profile
 */

namespace App\Http\Controllers\Profile;

use App\User;
use App\Login;
use IceTea\Http\Controller;
use App\Http\Controllers\Auth\CSRFToken;

class ChangePhoto extends Controller
{
	use CSRFToken;

	public function __construct()
	{
		parent::__construct();
	}

    public function index()
    {
    	//
    }

    public function run()
    {
    	if ($this->csrfValidation($_POST['csrf'])) {
    		$this->validateFile();
    		$this->savePhoto();
    		$this->update();
    	} else {
			abort(404);
    	}
    }

    private function validateFile()
    {
    	if (isset($_FILES['photo']['tmp_name'])) {
    		$checkimagesize = getimagesize($_FILES['photo']['tmp_name']);
    		if ($checkimagesize === false) {
    			http_response_code(400);
    			exit("<script>alert('Invalid file');window.location=''</script>");
    		}
    		
    		$extension = explode(".", $_FILES['photo']['name']);
    		if (! in_array($extension = strtolower(end($extension)), ["jpg", "png", "bmp", "gif"])) {
    			http_response_code(400);
    			exit("<script>alert('Invalid file extension');window.location=''</script>");
    		}
    		$filename  = sha1_file($_FILES['photo']['tmp_name']).".".$extension;
    		$realpath  = basepath('public/assets/img/users/'.$filename);
			if (
				file_exists($realpath) or 
				move_uploaded_file($_FILES['photo']['tmp_name'], $realpath)
			) {
				User::changePhoto(Login::getUserId(), $filename);
				exit("<script>alert('Success');window.location='/profile'</script>");
			} else {
				http_response_code(400);
    			exit("<script>alert('Internal error');window.location=''</script>");
			}
    	} else {
    		abort(404);
    	}
    	die;
    }
}
