<?php

/**
 *	Generated by IceTea Framework 0.0.1
 *	Created at 2017-12-14 15:50:38
 *	Namespace App\Http\Controllers\Profile
 */

namespace App\Http\Controllers\Profile;

use App\User;
use App\Login;
use IceTea\Http\Controller;
use App\Http\Controllers\Auth\CSRFToken;
;

class ChangePassword extends Controller
{
	public function __construct()
	{
		parent::__construct();
	}

    public function index()
    {
    	//
    }
}
