<?php

/**
 *	Generated by IceTea Framework 0.0.1
 *	Created at 2017-12-14 12:20:34
 *	Namespace App\Http\Controllers\Profile
 */

namespace App\Http\Controllers\Profile;

use IceTea\Http\Controller;
use App\Http\Controllers\Auth\CSRFToken;

class ChangeInfo extends Controller
{
	use CSRFToken;

	public function __construct()
	{
		parent::__construct();
	}

    public function index()
    {
    	//
    }

    public function run()
    {
    	$input = json_decode(file_get_contents("php://input"), true);
    	if (isset(
    		$input['first_name'],
    		$input['last_name'],
    		$input['username'],
    		$input['email'],
    		$input['csrf'],
    		$input['cost']
    	)) {
    		if ($this->csrfValidation($input['csrf'])) {
    			var_dump("valid");
    		}
    	}
    }
}
