<?php

/**
 *	Generated by IceTea Framework 0.0.1
 *	Created at 2017-12-14 14:02:23
 *	Namespace App\Http\Controllers\Profile
 */

namespace App\Http\Controllers\Profile;

use IceTea\Http\Controller;

class ChangePhoto extends Controller
{
	public function __construct()
	{
		parent::__construct();
	}

    public function index()
    {
    	//
    }
}
