<?php

/**
 *	Generated by IceTea Framework 0.0.1
 *	Created at 2017-12-13 23:14:40
 *	Namespace App\Http\Controllers
 */

namespace App\Http\Controllers;

use App\User;
use App\Chat;
use App\Login;
use IceTea\Http\Controller;

class ChatController extends Controller
{
	public function __construct()
	{
		parent::__construct();
	}

    public function index()
    {
    	return view('user/chat');
    }

    public function to($par)
	{
		return view('user/chat_end', [
			"info" => Chat::getChatInfo(Login::getUserId(), $par['username'])
		]);
	}

	public function get($par)
	{
		header("Content-type:application/json");
		print json_encode(Chat::getChatRoom(Login::getUserId(), $par['username']));
	}
}
