<?php

/**
 *  Generated by IceTea Framework 0.0.1
 *  Created at 2018-01-02 13:26:40
 *  Namespace App\Http\Controllers
 */

namespace App\Http\Controllers;

use IceTea\Http\Controller;

class ForgotPasswordController extends Controller
{
    public function __construct()
    {
        parent::__construct();
    }

    public function index()
    {
        //
    }
}
