<?php

/**
 *  Generated by IceTea Framework 0.0.1
 *  Created at 2017-11-12 09:59:52
 *  Namespace App\Http\Controllers
 */

namespace App\Http\Controllers;

use IceTea\Http\Controller;
use App\Http\Controllers\Auth\LoginController;

class IndexController extends Controller
{
    public function __construct()
    {
        parent::__construct();
    }

    public function index()
    {
        //
        if ($this->checkSession()) {
        } else {
            $login = new LoginController();
            return $login->loginPage();
        }
    }

    private function checkSession()
    {
        return false;
    }
}
