<?php

/**
 *  Generated by IceTea Framework 0.0.1
 *  Created at 2017-11-12 09:59:52
 *  Namespace App\Http\Controllers
 */

namespace App\Http\Controllers;

use App\User;
use App\Login;
use IceTea\Http\Controller;
use App\Http\Controllers\Auth\LoginController;

class IndexController extends Controller
{
    public function __construct()
    {
        parent::__construct();
    }

    public function index()
    {
        if (Login::isLoggedIn()) {
            return view('user/home', [
                "info" => User::getInfo(Login::getUserId(), "a.user_id")
            ]);
        } else {
            $login = new LoginController();
            return $login->loginPage();
        }
    }

	public function coba()
	{
		return view('user/cobacoba');
	}
}
