<?php

/**
 * Generated by EsTeh Framework {{ESTEH_VERSION}}
 * 2018-04-15 16:46:10
 */

namespace App\Http\Controllers;

use App\Http\Controllers\Controller;

class LoginController extends Controller
{
	public function index()
	{
		//
	}

	public function login()
	{
		echo 123;
	}
}
