<?php

/**
 *	Generated by IceTea Framework 0.0.1
 *	Created at 2017-12-14 10:50:05
 *	Namespace App\Http\Controllers
 */

namespace App\Http\Controllers;

use App\User;
use App\Login;
use IceTea\Http\Controller;
use App\Http\Controllers\Auth\CSRFToken;
use App\Http\Controllers\Auth\Authenticated;
use App\Http\Controllers\Profile\ChangeInfo;
use App\Http\Controllers\Profile\ChangePhoto;

class ProfileController extends Controller
{
	use CSRFToken;

	public function __construct()
	{
		parent::__construct();
	}

    public function index()
    {
        Authenticated::login();
    	$this->makeCSRF(600);
    	return view('user/profile', [
    		"info" => User::getInfo(Login::getUserId(), "a.user_id"),
    		"that" => $this
    	]);
    }

    public function changeInfo()
    {
        Authenticated::login();
        $subController = new ChangeInfo();
        $subController->run();
    }

    public function changePhotoPage()
    {
        Authenticated::login();
        $this->makeCSRF(600);
        return view('user/change_photo', [
            "info" => User::getInfo(Login::getUserId(), "a.user_id"),
            "that" => $this
        ]);
    }

    public function changePhoto()
    {
        Authenticated::login();
        $subController = new ChangePhoto();
        $subController->run();
    }
}
