<?php

/**
 *  Generated by IceTea Framework 0.0.1
 *  Created at 2017-11-18 13:14:19
 *  Namespace App\Http\Controllers
 */

namespace App\Http\Controllers;

use IceTea\Http\Controller;

class RegisterController extends Controller
{
    /**
     * Show register view.
     */
    public function index()
    {
        return view("auth/register");
    }

    /**
     * Action
     */
    public function action()
    {
    	$input = file_get_contents("php://input");
        $input = json_decode($input, true);
        if (isset(
            $input['first_name'], 
            $input['last_name'], 
            $input['email'],
            $input['username'],
            $input['password'],
            $input['confirm_password']
        ) && $this->isValidDevice()) {
            $this->validator($input);
        } else {
            abort(404);
        }
    }

    private function isValidDevice()
    {
        return true;
    }

    private function validator($input)
    {
        var_dump($input);
    }
}
