<?php

/**
 *  Generated by IceTea Framework 0.0.1
 *  Created at 2017-11-18 13:14:19
 *  Namespace App\Http\Controllers
 */

namespace App\Http\Controllers;

use IceTea\Http\Controller;

class RegisterController extends Controller
{
    public function __construct()
    {
        parent::__construct();
    }

    public function index()
    {
        //
        return view("auth/register");
    }
}
